import Head from "next/head"
import Image from "next/image"

const About = () => {
    return(
        <>
            <Head>
                <title>Transnet || Tentang</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <div className="container px-4 md:px-20 m-auto mt-20 font-[Poppins]">
                <div className="mt-28 flex justify-around">
                    <Image className="w-full h-[300px] object-cover" src="/img/tentang.jpg" width={400} height={0} />
                </div>

                <div className="mt-10">
                    <h1 className="font-semibold text-2xl md:text-3xl">Budaya Perusahaan</h1>
                    <p className="mt-5 text-sm md:text-base leading-relaxed text-black/70">
                        TRANSNET akan selalu berupaya untuk memberikan layanan terbaik untuk 
                        seluruh pelanggan dan mitra perusahaan dengan mengedepankan nilai-nilai 
                        perusahaan demi terwujudnya hubungan kemitraan yang baik. 
                        Adapun budaya perusahaan yang kami terapkan antara lain:
                    </p>

                    <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-5 mt-10 px-8">
                        <div className="bg-white shadow-md p-5 rounded-md cursor-pointer">
                            <h1 className="text-xl text-center font-semibold">Good Governance</h1>
                            <p className="text-center text-sm mt-2 text-black/75">
                                Menyelenggarakan manajemen pembangunan yang solid
                                dan bertanggung jawab yang sejalan dengan prinsip
                                lingkungan dan pasar yang efisien
                            </p>
                        </div>
                        <div className="bg-white shadow-md p-5 rounded-md cursor-pointer">
                            <h1 className="text-xl text-center font-semibold">Professional</h1>
                            <p className="text-center text-sm mt-2 text-black/75">
                                Bersikap professional dengan terikat pada
                                standar standar layanan dan protokol layanan
                                terbaik kepada pelanggan
                            </p>
                        </div>
                        <div className="bg-white shadow-md p-5 rounded-md cursor-pointer">
                            <h1 className="text-xl text-center font-semibold">Partnership Priority</h1>
                            <p className="text-center text-sm mt-2 text-black/75">
                                Memberikan prioritas pada kebutuhan mitra dan 
                                pelanggan dengan berprinsip pada metode 
                                kerjasama yang baik dan efisien
                            </p>
                        </div>
                        <div className="bg-white shadow-md p-5 rounded-md cursor-pointer">
                            <h1 className="text-xl text-center font-semibold">Discipline</h1>
                            <p className="text-center text-sm mt-2 text-black/75">
                                Merupakan nilai-nilai disiplin yang sesuai dengan
                                rencana-rencana yang strategis untuk mewujudkan tujuan perusahaan 
                            </p>
                        </div>
                        <div className="bg-white shadow-md p-5 rounded-md cursor-pointer">
                            <h1 className="text-xl text-center font-semibold">Quality</h1>
                            <p className="text-center text-sm mt-2 text-black/75">
                                Berupaya memberikan kualitas dengan mutu pelayanan
                                terbaik kepada pelanggan untuk memberikan pengalaman 
                                berselancar yang nyaman.
                            </p>
                        </div>
                        <div className="bg-white shadow-md p-5 rounded-md cursor-pointer">
                            <h1 className="text-xl text-center font-semibold">Collaboration</h1>
                            <p className="text-center text-sm mt-2 text-black/75">
                                Kami berkolaborasi dengan mitra-mitra perusahaan untuk menciptakan
                                tim yang kuat dan memberikan solusi dan kualitas layanan terbaik
                                kepada pelanggan.
                            </p>
                        </div>
                    </div>
                    <hr className="w-1/3 mt-20 m-auto border-2 border-black" />
                    <h1 className="text-xl font-semibold text-center mt-4">Area Jangakauan</h1>
                    <hr className="w-1/3 mt-4 m-auto border-2 border-black" />
                    <p className="w-1/2 text-center mt-8 m-auto text-black/80">
                        Saat ini pengembangan kami adalah pengembangan infrastruktur jaringan
                        dan area support di area kawasan indonesia timur.
                    </p>
                </div>
            </div>
        </>
    )
}

export default About