import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';

export default function Home() {
  return (
    <>
      <Head>
        <title>Transnet</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="px-4 md:px-10 lg:px-16 font-[Poppins] pb-20">
        <div className="mt-28 flex justify-around">
          <div className="bg-[url('/img/home.jpg')] rounded-lg bg-center text-center w-full p-14">
            <h1 className="text-4xl my-10 text-white font-semibold items-center">Akses Internet <br /> Tanpa Batas</h1>
            <Link href="/contact" className="bg-blue-600 hover:bg-blue-700 transition duration-400 text-sm rounded-md px-5 py-3 text-white font-semibold">
              Kontak kami
            </Link>
          </div>
        </div>

        <div className="mt-20 pb-10">
          <h1 className="text-2xl font-semibold">Kini Hadir</h1>
          <p className="mt-3 w-[80%] text-gray-700 leading-relaxed">
            PT Trans Nasional Teknologi hadir dengan brand produk TRANSNET sebagai perusahaan telekomunikasi yang melayani koneksi internet ke seluruh dunia dengan infrastruktur jaringan serat optik, jaringan wireless (radio) yang menjangkau area kota Makassar dan sekitarnya, serta jaringan satelit hingga ke daerah pelosok di Indonesia bagian timur.
          </p>
        </div>

        <hr />

        <div className="mt-10 pb-20 flex flex-col gap-7">
          <div className="flex gap-7 bg-white shadow-xl p-7 rounded-xl">
            <Image src="/img/paket1.png" className="rounded-2xl w-1/2" width={500} height={0} />
            <div className="w-1/2">
              <h1 className="text-3xl font-semibold">Internet Corporated <br />Dedicated</h1>
              <p className="mt-4 leading-loose text-gray-800">
              Layanan Internet Corporate Dedicated Access adalah layanan akses internet yang diberikan kepada Pelanggan korporasi dengan rasio bandwidth 1:1 dan layanan support 24/7.
              </p>
            </div>
          </div>

          <div className="flex gap-7 flex-row-reverse justify-between bg-white shadow-xl p-7 rounded-xl">
            <Image src="/img/paket2.png" className="rounded-2xl w-1/2" width={500} height={0} />
            <div className="w-1/2">
              <h1 className="text-3xl font-semibold">Internet Home <br />Unlimited</h1>
              <p className="mt-4 leading-loose text-gray-800">
              Layanan Internet Unlimited Access adalah layanan akses internet yang diberikan umtuk kebutuhan bisnis dan keluarga seluruh Indonesia dengan akses internet ke seluruh dunia tanpa batas. 
              </p>
            </div>
          </div>
        </div>

        <hr />

        <div className="mt-24">
          <h1 className="text-3xl font-semibold text-center">Layanan</h1>

          <div className="grid grid-cols-3 gap-4 mt-10">
            <div className="bg-white p-5 font-semibold hover:shadow-lg rounded-lg transition duration-400 cursor-pointer text-center">
              <i className="bi bi-alarm text-2xl"></i>
              <h1 className="text-lg mt-4">Dukungan 24 jam</h1>
              <p className="mt-3 text-sm text-black/60 leading-loose">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
            </div>
            <div className="bg-white p-5 font-semibold hover:shadow-lg rounded-lg transition duration-400 cursor-pointer text-center">
              <p className="text-black/75">IP</p>
              <h1 className="text-lg mt-4">Free IP public</h1>
              <p className="mt-3 text-sm text-black/60 leading-loose">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
            </div>
            <div className="bg-white p-5 font-semibold hover:shadow-lg rounded-lg transition duration-400 cursor-pointer text-center">
              <i class="bi bi-gear-fill text-2xl"></i>
              <h1 className="text-lg mt-4">Service agreement 99%</h1>
              <p className="mt-3 text-sm text-black/60 leading-loose">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
            </div>
            <div className="bg-white p-5 font-semibold hover:shadow-lg rounded-lg transition duration-400 cursor-pointer text-center">
              <i class="bi bi-wifi text-2xl"></i>
              <h1 className="text-lg mt-4">Kondisi infrastruktur</h1>
              <p className="mt-3 text-sm text-black/60 leading-loose">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
            </div>
          </div>
        </div>
      </div>
    </>
  )
}
